name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKER_PASSWORD}} | docker login -u ${{ secrets.DOCKER_USERNAME}} --password-stdin
    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/commentfilter .
    - name: Publish to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/commentfilter
