name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKER_PASSWORD}} | docker login -u ${{ secrets.DOCKER_USERNAME}} --password-stdin
    - name: Build the Docker images
      run: |
        docker-compose build
        docker tag commentfilter_tensorflow ${{ secrets.DOCKER_USERNAME }}/tensorflow
        docker tag commentfilter_nodewebsite ${{ secrets.DOCKER_USERNAME }}/nodewebsite
        docker tag commentfilter_loadbalancer ${{ secrets.DOCKER_USERNAME }}/loadbalancer

    - name: Publish to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/tensorflow
        docker push ${{ secrets.DOCKER_USERNAME }}/nodewebsite
        docker push ${{ secrets.DOCKER_USERNAME }}/loadbalancer

      
